/* Plugin generated by AMXX-Studio */

#include < amxmodx >
#include < amxmisc >
#include < cstrike >
#include < csx >
#include < engine >
#include < fakemeta >
#include < hamsandwich >
#include < sqlx >
#include < basicstatsconnect >

#define PLUGIN "Basic Points Stats"
#define VERSION "2.4.4"
#define AUTHOR 	"Google Gemini, kwpd"

#define ADMIN ADMIN_RCON
#define MAXPLAYERS 32
#define CONNECT_TASK1 1021
#define CONNECT_TASK2 1022
#define CONNECT_TASK3 1023

#define CheckUserIgnored(%1)	( g_bIgnored &   ( 1 << ( %1 & 31 ) ) )
#define IsPlayer(%1)		( 1 <= %1 <= g_iMaxPlayers )

new g_iMaxPlayers
new g_szAuthID[ MAX_PLAYERS ][ 35 ]
new g_szName[ MAX_PLAYERS ][ 8 ]
new Handle:g_SqlTuple

new g_pcvarHost
new g_pcvaruUser
new g_pcvarPass 
new g_pcvarDB 

// new g_iCount
// new g_iRank[ MAX_PLAYERS ]

new g_iCurrentKills[ MAX_PLAYERS ]
new g_iCurrentKills_v[ MAX_PLAYERS ]

new g_bIgnored

new g_szPoints[ MAX_PLAYERS ]
new g_szLevels[ MAX_PLAYERS ]
new g_szPoints_k[ MAX_PLAYERS ]
new g_szPoints_d[ MAX_PLAYERS ]
new g_szPoints_a[ MAX_PLAYERS ]
new g_szPoints_bp[ MAX_PLAYERS ]
new g_szPoints_bd[ MAX_PLAYERS ]
new g_szPoints_adr[ MAX_PLAYERS ]
new g_szPoints_hsp[ MAX_PLAYERS ]
new g_szPoints_rws[ MAX_PLAYERS ]
new g_szPoints_win[ MAX_PLAYERS ]
new g_szPoints_los[ MAX_PLAYERS ]
new g_szPoints_tied[ MAX_PLAYERS ]
new g_szPoints_r_los[ MAX_PLAYERS ]
new g_szPoints_rp[ MAX_PLAYERS ]

// PISTOL
new g_szCSW_GLOCK18[ MAX_PLAYERS ]
new g_szCSW_USP[ MAX_PLAYERS ]
new g_szCSW_P228[ MAX_PLAYERS ]
new g_szCSW_DEAGLE[ MAX_PLAYERS ]
new g_szCSW_ELITE[ MAX_PLAYERS ]
new g_szCSW_FIVESEVEN[ MAX_PLAYERS ]
new g_szCSW_KNIFE[ MAX_PLAYERS ]
new g_szCSW_HEGRENADE[ MAX_PLAYERS ]
new g_szCSW_C4[ MAX_PLAYERS ]

// ARMAS
new g_szCSW_M3[ MAX_PLAYERS ]
new g_szCSW_XM1014[ MAX_PLAYERS ]
new g_szCSW_TMP[ MAX_PLAYERS ]
new g_szCSW_UMP45[ MAX_PLAYERS ]
new g_szCSW_MAC10[ MAX_PLAYERS ]
new g_szCSW_MP5NAVY[ MAX_PLAYERS ]
new g_szCSW_P90[ MAX_PLAYERS ]
new g_szCSW_GALIL[ MAX_PLAYERS ]
new g_szCSW_FAMAS[ MAX_PLAYERS ]
new g_szCSW_AK47[ MAX_PLAYERS ]
new g_szCSW_M4A1[ MAX_PLAYERS ]
new g_szCSW_SCOUT[ MAX_PLAYERS ]
new g_szCSW_SG552[ MAX_PLAYERS ]
new g_szCSW_AWP[ MAX_PLAYERS ]
new g_szCSW_G3SG1[ MAX_PLAYERS ]
new g_szCSW_AUG[ MAX_PLAYERS ]
new g_szCSW_SG550[ MAX_PLAYERS ]
new g_szCSW_M249[ MAX_PLAYERS ]

// Versus
new g_szPoints_2k[ MAX_PLAYERS ]
new g_szPoints_3k[ MAX_PLAYERS ]
new g_szPoints_4k[ MAX_PLAYERS ]
new g_szPoints_5k[ MAX_PLAYERS ]
new g_szPoints_v1[ MAX_PLAYERS ]
new g_szPoints_v2[ MAX_PLAYERS ]
new g_szPoints_v3[ MAX_PLAYERS ]
new g_szPoints_v4[ MAX_PLAYERS ]
new g_szPoints_v5[ MAX_PLAYERS ]

// new bool:is_user_ignored[ MAX_PLAYERS ]
new bool:g_bRoundEnded

new pcvarToggle1
new pcvarToggle2

new pug_dmg[MAX_PLAYERS + 1][MAX_PLAYERS + 1]
new bps_players[ MAX_PLAYERS ]
new bps_playersx[ MAX_PLAYERS ]
new bps_players_round_save[ MAX_PLAYERS ]
new bps_players_versus[ MAX_PLAYERS ]
new pcvarToggle_stats
// new bps_players_authorized[32]

public plugin_init()
{
	register_plugin( PLUGIN, VERSION, AUTHOR )
	register_dictionary("BasicPointsStats.txt")
	
	g_pcvarHost = register_cvar( "bps_sql_host", "peak.evolution-host.com:3306", FCVAR_PROTECTED )
	g_pcvaruUser = register_cvar( "bps_sql_user", "u451_I2EqpJTTR4", FCVAR_PROTECTED )
	g_pcvarPass = register_cvar( "bps_sql_pass", "jDwx!V8OHzv@MWPV1Lts6.Pk", FCVAR_PROTECTED )
	g_pcvarDB = register_cvar( "bps_sql_db", "s451_SkillPointsBeta", FCVAR_PROTECTED )
	
	register_cvar( "bps_sql_db_1", "basicpointsstats" )
	register_cvar( "bps_sql_db_2", "basicweapomstats1" )
	register_cvar( "bps_sql_db_3", "basicweapomstats2" )
	register_cvar( "bps_sql_db_4", "basicversusstats" )
	register_cvar( "bps_sql_temp_db", "skillpoints_pug1" )
	register_cvar( "pug_web_top_pug", "http://186.66.21.118:8081/web/top15.php" )
	register_cvar( "pug_web_temp_pug", "http://186.66.21.118:8081/WEB/" )
	
	register_clcmd("say", "stats_pug")
	register_clcmd("say_team", "stats_pug")
	
	pcvarToggle1 = register_cvar("pug_leave_points", "0")
	pcvarToggle2 = register_cvar("pug_stats_enable", "1")
	
	register_concmd("pug_end_stats", "motd_pug_end", ADMIN, "_")
	register_concmd("bps_give_pugend", "points_all_pugend", ADMIN, "_")
	register_concmd("amx_bps_ctwin", "points_win_ct", ADMIN, "_")
	register_concmd("amx_bps_twin", "points_win_t", ADMIN, "_")
	register_concmd("amx_bps_tie", "points_tied", ADMIN, "_")
	
	register_event( "SendAudio", "TerroristsWin", "a", "2&%!MRAD_terwin" )
	register_event( "SendAudio", "CounterTerroristsWin", "a", "2&%!MRAD_ctwin" )
	register_event( "SendAudio", "Event_RoundDraw", "a", "2&%!MRAD_rounddraw")
	
	//register_clcmd("joinclass","evento_joinclass","a")
	register_event("TeamInfo", "join_team", "a")
	// register_event("DeathMsg","cmd_death","ae")
	register_event( "HLTV", "EventNewRound", "a", "1=0", "2=0" )
	register_logevent("EventRoundEnd", 2, "1=Round_End")
	
	
	RegisterHam(Ham_TakeDamage, "player", "FwdPlayerDamagePost", 1)
	RegisterHam(Ham_Killed, "player", "Ham_Killed_player")
	RegisterHam(Ham_Spawn, "player", "FwdPlayerSpawnPost", 1)
	
	g_iMaxPlayers = get_maxplayers( )
	
	SqlInit()
}

public SqlInit()
{
	new TEMP_SQL_TABLE[256]
	get_cvar_string("bps_sql_temp_db",TEMP_SQL_TABLE,256)
	
	new szHost[ 32 ]
	new szUser[ 32 ]
	new szPass[ 32 ]
	new szDB[ 32 ]
	
	get_pcvar_string( g_pcvarHost, szHost, charsmax( szHost ) )
	get_pcvar_string( g_pcvaruUser, szUser, charsmax( szUser ) )
	get_pcvar_string( g_pcvarPass, szPass, charsmax( szPass ) )
	get_pcvar_string( g_pcvarDB, szDB, charsmax( szDB ) )
	
	g_SqlTuple = SQL_MakeDbTuple( szHost, szUser, szPass, szDB )
	
	new g_Error[ 512 ]
	new ErrorCode
	new Handle:SqlConnection = SQL_Connect( g_SqlTuple, ErrorCode, g_Error, charsmax( g_Error ))
	
	if( SqlConnection == Empty_Handle )
	{
		set_fail_state( g_Error )
	}
	new Handle:Queries
	Queries = SQL_PrepareQuery( SqlConnection, "DROP TABLE IF EXISTS %s", TEMP_SQL_TABLE )
	
	if( !SQL_Execute( Queries ) )
	{
		SQL_QueryError(Queries, g_Error, charsmax(g_Error))
		set_fail_state(g_Error)
	}
	
	SQL_FreeHandle( Queries )
	SQL_FreeHandle( SqlConnection )
	return PLUGIN_CONTINUE
}

public plugin_end()
{
	SQL_FreeHandle( g_SqlTuple )
}

public client_authorized( id )
{
	get_user_authid( id , g_szAuthID[id], charsmax( g_szAuthID[ ] ) )
	get_user_info( id, "name", g_szName[id], charsmax( g_szName[ ] ) )
	
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "'", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "^"", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "`", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "´", "*" )
}
public client_connect(id)
{
	if(is_user_bot(id) || is_user_hltv(id))
	{
		return PLUGIN_HANDLED;
		} else {
		bps_players[id] = 15
		bps_playersx[id] = 15
		bps_players_round_save[id] = 10
		// server_cmd("say Jugador conectandose")
		return PLUGIN_CONTINUE
	}
}

public client_putinserver( id )
{
	if(is_user_bot(id) || is_user_hltv(id))
	{
		return PLUGIN_HANDLED;
		} else {
		bps_players[id] = 15
		bps_playersx[id] = 15
		bps_players_round_save[id] = 10
		bps_players_versus[id] = 0
		g_iCurrentKills[id] = 0
		g_iCurrentKills_v[id] = 0
		// server_cmd("say JUGADOR CONECTADO")
		return PLUGIN_CONTINUE
	}
}

public join_team(id)
{
	new id = read_data(1)
	static user_team[32]
	read_data(2, user_team, 31)
	
	if(!is_user_connected(id))
		return PLUGIN_CONTINUE
	
	switch(user_team[0])
	{
		case 'T': 
		{
			if(bps_playersx[id] == 15) {
				bps_playersx[id] = 1
				set_task( 0.5, "Test_client_authorized", id + CONNECT_TASK2 )
				// client_print(id, print_chat, "BPS - *ENTRADA AL EQUIPO Authorized Terroris* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_JOIN_T")
			}
			return PLUGIN_CONTINUE
		}
		case 'C':
		{
			if(bps_playersx[id] == 15) {
				bps_playersx[id] = 1
				set_task( 0.5, "Test_client_authorized", id + CONNECT_TASK2 )
				// client_print(id, print_chat, "BPS - *ENTRADA AL EQUIPO Authorized CTs* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_JOIN_CT")
			}
			return PLUGIN_CONTINUE
		}
		case 'S':
		{
			if(bps_playersx[id] == 15) {
				bps_playersx[id] = 15
				// client_print(id, print_chat, "BPS - *ENTRADA AL EQUIPO NO Authorized SPECTADOR* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_JOIN_S")
			}
			return PLUGIN_CONTINUE
		}
	}
	if(bps_players[id] == 1)
	{
		// client_print(id, print_chat, "BPS - *ENTRADA AL EQUIPO Autirized* PASSE.!")
		client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_REJOIN")
		return PLUGIN_CONTINUE
	}
	return PLUGIN_CONTINUE
}

public Test_client_authorized(id)
{
	id -= CONNECT_TASK2
	
	LoadPoints1(id)
	LoadPoints2(id)
	LoadPoints3(id)
	LoadPoints4(id)
}

public Test_bps_players(id)
{
	bps_players[id] = 1
	// client_print( id, print_chat, "BPS - *SET Players ID = 1* PASSE.!")
	client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_SET_ID_1")
	return PLUGIN_CONTINUE
}

public client_infochanged( id )
{
	if( is_user_connected(id) || !task_exists( id + CONNECT_TASK1 ) || !task_exists( id + CONNECT_TASK2 ) )
	{
		new szNewName[ 32 ]
		get_user_info( id, "name", szNewName, charsmax( szNewName ) ) 
		new iLen = strlen( szNewName )
		new iPos = iLen - 1
		if( szNewName[ iPos ] == '>' )
		{
			new i
			for( i = 1; i < 7; i++ )
			{
				if( szNewName[ iPos - i ] == '<' )
				{
					iLen = iPos - i
					szNewName[ iLen ] = EOS
					break
				}
			}
		}
		trim( szNewName )
		if( !equal( g_szName[ id ], szNewName ) )
		{
			copy( g_szName[ id ], charsmax( g_szName[ ] ), szNewName )
			
			replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "'", "*" )
			replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "^"", "*" )
			replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "`", "*" )
			replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "´", "*" )
		}
	}
	return PLUGIN_CONTINUE
}

public client_disconnected(id)
{
	if(bps_players[id] == 1)
	{
		remove_task( id )
		remove_task( id + CONNECT_TASK1 )
		remove_task( id + CONNECT_TASK2 )
		remove_task( id + CONNECT_TASK3 )
		bps_players_versus[id] = 0
		g_szPoints[ id ] -= get_pcvar_num(pcvarToggle1)
		CheckLevelAndSave1(id)
		CheckLevelAndSave2(id)
		CheckLevelAndSave3(id)
		CheckLevelAndSave4(id)
		// server_cmd("say Se Grabo al salir")
		return PLUGIN_CONTINUE
		} else {
		remove_task( id )
		remove_task( id + CONNECT_TASK1 )
		remove_task( id + CONNECT_TASK2 )
		remove_task( id + CONNECT_TASK3 )
		// server_cmd("say Se removio los TASK ID")
		return PLUGIN_CONTINUE
	}
}

public client_death(killer, victim, wpnindex, hitplace, TK)
{
	// Validaciones iniciales (Guard Clauses) para evitar errores, autolesiones y Team Kills
	if (!IsPlayer(killer) || !IsPlayer(victim) || killer == victim || TK)
	{
		return PLUGIN_CONTINUE;
	}
	
	// Verificamos si el sistema de puntos general está activo y si el killer no está ignorado
	if (bps_players[killer] == 1 && get_pcvar_num(pcvarToggle2) && !CheckUserIgnored(killer))
	{
		// Estadísticas básicas generales de bajas
		g_iCurrentKills[killer]++;
		g_szPoints_k[killer]++;
		
		// --- 1. REGISTRO DE ESTADÍSTICAS POR ARMA (WPNINDEX) ---
		switch (wpnindex)
		{
			// Pistolas y equipamiento menor
			case CSW_GLOCK18:   { g_szCSW_GLOCK18[killer]++; }
			case CSW_USP:       { g_szCSW_USP[killer]++; }
			case CSW_P228:      { g_szCSW_P228[killer]++; }
			case CSW_DEAGLE:    { g_szCSW_DEAGLE[killer]++; }
			case CSW_ELITE:     { g_szCSW_ELITE[killer]++; }
			case CSW_FIVESEVEN:{ g_szCSW_FIVESEVEN[killer]++; }
			case CSW_KNIFE:     { g_szCSW_KNIFE[killer]++; }
			case CSW_HEGRENADE:{ g_szCSW_HEGRENADE[killer]++; }
			case CSW_C4:        { g_szCSW_C4[killer]++; }
			
			// Escopetas y Subfusiles (SMGs)
			case CSW_M3:        { g_szCSW_M3[killer]++; }
			case CSW_XM1014:    { g_szCSW_XM1014[killer]++; }
			case CSW_TMP:       { g_szCSW_TMP[killer]++; }
			case CSW_UMP45:     { g_szCSW_UMP45[killer]++; }
			case CSW_MAC10:     { g_szCSW_MAC10[killer]++; }
			case CSW_MP5NAVY:   { g_szCSW_MP5NAVY[killer]++; }
			case CSW_P90:       { g_szCSW_P90[killer]++; }
			
			// Rifles de asalto y francotiradores
			case CSW_GALIL:     { g_szCSW_GALIL[killer]++; }
			case CSW_FAMAS:     { g_szCSW_FAMAS[killer]++; }
			case CSW_AK47:      { g_szCSW_AK47[killer]++; }
			case CSW_M4A1:      { g_szCSW_M4A1[killer]++; }
			case CSW_SCOUT:     { g_szCSW_SCOUT[killer]++; }
			case CSW_SG552:     { g_szCSW_SG552[killer]++; }
			case CSW_AWP:       { g_szCSW_AWP[killer]++; }
			case CSW_G3SG1:     { g_szCSW_G3SG1[killer]++; }
			case CSW_AUG:       { g_szCSW_AUG[killer]++; }
			case CSW_SG550:     { g_szCSW_SG550[killer]++; }
			case CSW_M249:      { g_szCSW_M249[killer]++; }
		}
		
		// --- 3. LÓGICA DE VERSUS (CLUTCH) ---
		new iKillerTeam = _:cs_get_user_team(killer);
		
		if (iKillerTeam == _:CS_TEAM_T || iKillerTeam == _:CS_TEAM_CT)
		{
			new enemies[32], num_enemies;
			get_players(enemies, num_enemies, "ae", (iKillerTeam == _:CS_TEAM_T) ? "CT" : "TERRORIST");
			
			new teammates[32], num_teammates;
			get_players(teammates, num_teammates, "ae", (iKillerTeam == _:CS_TEAM_T) ? "TERRORIST" : "CT");
			
			// Si el número de compañeros vivos es 1 (el propio asesino)
			if (num_teammates <= 1)
			{
				switch (num_enemies)
				{
					case 1: { g_szPoints_v1[killer]++; g_szPoints[killer] += 3; }  // 1v1
					case 2: { g_szPoints_v2[killer]++; g_szPoints[killer] += 5; }  // 1v2
					case 3: { g_szPoints_v3[killer]++; g_szPoints[killer] += 7; }  // 1v3
					case 4: { g_szPoints_v4[killer]++; g_szPoints[killer] += 10; } // 1v4
					default: {
						if (num_enemies >= 5) 
						{ 
							g_szPoints_v5[killer]++; 
							g_szPoints[killer] += 15; // 1v5 o superior
						}
					}
				}
			}
		}
	}
	
	// Estadísticas secundarias de víctima y headshots
	if (!CheckUserIgnored(victim) && wpnindex != CSW_C4)
	{
		g_szPoints_d[victim] += 1;
	}
	
	if (hitplace == HIT_HEAD && wpnindex != CSW_KNIFE)
	{
		g_szPoints_hsp[killer] += 1;
	}
	
	return PLUGIN_CONTINUE;
}

public Ham_Killed_player(iVictim, iAttacker, shouldgib) 
{
	new i = 1; // Por seguridad en AMX Mod X, usualmente los index de jugadores empiezan en 1
	do {
		if (i != iAttacker && i != iVictim) 
		{
			if (pug_dmg[i][iVictim] > 30) 
			{
				assist(i, iVictim);
			}
		}
		i += 1;
	} while (i <= MaxClients); // Es mejor usar MaxClients en lugar de un número fijo como 33
}

public assist(attacker, victim)
{
	pug_dmg[attacker][victim] = 0
	g_szPoints_a[attacker]++
	g_szPoints[attacker] += 2
}

public FwdPlayerSpawnPost(iPlayer) 
{
	if (!is_user_connected(iPlayer))
		return;
	
	// Limpiamos los contadores del jugador que reaparece
	g_iCurrentKills[iPlayer] = 0;
	g_iCurrentKills_v[iPlayer] = 0;
	
	// Limpiamos el almacenamiento de daño que hizo o recibió este jugador
	for (new i = 1; i <= MaxClients; i++) 
	{
		pug_dmg[iPlayer][i] = 0;
	}
}

public FwdPlayerDamagePost(victim, inflictor, attacker, Float:damage, bits)
{
	// Validamos que el atacante sea un jugador y que no sea la misma persona (auto-daño / propia granada)
	if (IsPlayer(attacker) && victim != attacker)
	{
		// Validamos que pertenezcan a equipos contrarios para evitar el daño amigo (Team Damage)
		if (cs_get_user_team(victim) != cs_get_user_team(attacker))
		{
			pug_dmg[attacker][victim] += damage;
			g_szPoints_adr[attacker] += damage;
		}
	}
}

stock Float:get_percent(iTotal, iParcial) 
{
	if (iTotal <= 0) return 0.0; // Protección contra división por cero
	return float((iParcial * 100.0) / iTotal);
}

public TerroristsWin()
{
	// 1. Verificamos si la ronda ya terminó o si el sistema general de puntos está desactivado
	if (g_bRoundEnded || !get_pcvar_num(pcvarToggle2))
	{
		return PLUGIN_CONTINUE;
	}
	
	new Players[MAXPLAYERS];
	new iNum;
	
	// Obtenemos solo a los jugadores conectados y que no sean espectadores ("ch")
	get_players(Players, iNum, "ch");
	
	for (new i, id; i < iNum; i++)
	{
		id = Players[i];
		
		// Verificamos si el jugador tiene el sistema activo (usamos 'continue' en lugar de 'return' para no romper el bucle)
		if (bps_players[id] != 1)
		{
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15");
			continue; // Salta al siguiente jugador sin detener la función
		}
		
		// Lógica según el bando ganador (Terroristas)
		switch (cs_get_user_team(id))
		{
			case CS_TEAM_T: 
			{
				bps_players_round_save[id] = 1;
				g_szPoints[id] += 1;
				g_szPoints_rws[id] += 1;
				g_szPoints_rp[id] += 1;
				
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1");
			}
			case CS_TEAM_CT: 
			{
				bps_players_round_save[id] = 1;
				bps_players_versus[id] = 0;
				g_szPoints_r_los[id] += 1;
				
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1");
			}
		}
	}
	
	g_bRoundEnded = true;
	return PLUGIN_CONTINUE;
}

public CounterTerroristsWin()
{
	// 1. Verificamos si la ronda ya terminó o si el sistema general de puntos está desactivado
	if (g_bRoundEnded || !get_pcvar_num(pcvarToggle2))
	{
		return PLUGIN_CONTINUE;
	}
	
	new Players[MAXPLAYERS];
	new iNum;
	
	// Obtenemos solo a los jugadores conectados y que no sean espectadores ("ch")
	get_players(Players, iNum, "ch");
	
	for (new i, id; i < iNum; i++)
	{
		id = Players[i];
		
		// Verificamos si el jugador tiene el sistema activo (usamos 'continue' para no romper el bucle)
		if (bps_players[id] != 1)
		{
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15");
			continue; // Salta al siguiente jugador de forma segura
		}
		
		// Lógica según el bando ganador (Counter-Terrorists)
		switch (cs_get_user_team(id))
		{
			case CS_TEAM_T: 
			{
				bps_players_round_save[id] = 1;
				bps_players_versus[id] = 0;
				g_szPoints_r_los[id] += 1;
				
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1");
			}
			case CS_TEAM_CT: 
			{
				bps_players_round_save[id] = 1;
				g_szPoints[id] += 1;
				g_szPoints_rws[id] += 1;
				g_szPoints_rp[id] += 1;
				
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1");
			}
		}
	}
	
	g_bRoundEnded = true;
	return PLUGIN_CONTINUE;
}

public Event_RoundDraw()
{
	// 1. Verificamos si la ronda ya terminó o si el sistema general de puntos está desactivado
	if (g_bRoundEnded || !get_pcvar_num(pcvarToggle2))
	{
		return PLUGIN_CONTINUE;
	}
	
	new Players[MAXPLAYERS];
	new iNum;
	
	// Obtenemos solo a los jugadores conectados y que no sean espectadores ("ch")
	get_players(Players, iNum, "ch");
	
	for (new i, id; i < iNum; i++)
	{
		id = Players[i];
		
		// Verificamos si el jugador tiene el sistema activo
		if (bps_players[id] != 1)
		{
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15");
			continue; // Salta al siguiente jugador de forma segura sin romper el bucle
		}
		
		// En caso de empate (Round Draw), ambos equipos reciben el estado configurado (15)
		switch (cs_get_user_team(id))
		{
			case CS_TEAM_T, CS_TEAM_CT: 
			{
				bps_players_round_save[id] = 15;
			}
		}
	}
	
	g_bRoundEnded = true;
	return PLUGIN_CONTINUE;
}

public points_all_pugend( id, level, cid )
{
	if ( !cmd_access( id, level, cid, 1 )) return PLUGIN_HANDLED
	
	new Players[ MAXPLAYERS ]
	new iNum
	new i
	get_players( Players, iNum, "ch" )
	for( --iNum; iNum >= 0; iNum-- )
	{
		i = Players[ iNum ]
		if( !CheckUserIgnored( i ))
		{
			g_szPoints[ i ] += 15
		}
	}
	if(bps_players[id] == 15)
	{
		// client_print(id, print_chat, "BPS - *MINIMO Point All END* PASSE.!")
		client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
	}
	return PLUGIN_CONTINUE
}

public points_win_ct( id, level, cid )
{
	if ( !cmd_access( id, level, cid, 1 )) return PLUGIN_HANDLED
	
	new Players[ MAXPLAYERS ]
	new iNum
	new i
	get_players( Players, iNum, "ch" )
	for( --iNum; iNum >= 0; iNum-- )
	{
		i = Players[ iNum ]
		if(bps_players[i] == 15)
		{
			// client_print(id, print_chat, "BPS - *TERRORIS = ID = 15 Desactivado* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
		if(bps_players[i] == 1)
		{
			if( get_pcvar_num( pcvarToggle2 ) )
			{
				if( !CheckUserIgnored( i ))
				{
					switch( cs_get_user_team( i ))
					{
						case( CS_TEAM_T ):
						{
							g_szPoints_r_los[ i ] += 1
							bps_players_versus[ i ] = 0
						}
						case( CS_TEAM_CT ):
						{
							g_szPoints_rws[ i ] += 1
							g_szPoints_rp[ i ] += 1
						}
					}
					// client_print(id, print_chat, "BPS - *TERRORIS = ID = 1 Activado* PASSE.!")
					client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1")
					return PLUGIN_CONTINUE
				}
			}
			else {
				// client_print(id, print_chat, "BPS - *EL STATS, ESTA DESACTIVADO* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_OFF_ID")
				return PLUGIN_CONTINUE
			}
		}
		else {
			// client_print(id, print_chat, "BPS - *NO TIENES EL ID=1* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
	}
	return PLUGIN_CONTINUE
}

public points_win_t( id, level, cid )
{
	if (!cmd_access( id, level, cid, 1 )) return PLUGIN_HANDLED
	
	new Players[ MAXPLAYERS ]
	new iNum
	new i
	
	get_players( Players, iNum, "ch" )
	for( --iNum; iNum >= 0; iNum-- )
	{
		i = Players[ iNum ]
		if(bps_players[i] == 15)
		{
			// client_print(id, print_chat, "BPS - *TERRORIS = ID = 15 Desactivado* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
		if(bps_players[i] == 1)
		{
			if( get_pcvar_num( pcvarToggle2 ) )
			{
				if( !CheckUserIgnored( i ))
				{
					switch( cs_get_user_team( i ))
					{
						case( CS_TEAM_T ):
						{
							g_szPoints_rws[ i ] += 1
							g_szPoints_rp[ i ] += 1
						}
						case( CS_TEAM_CT ):
						{
							g_szPoints_r_los[ i ] += 1
							bps_players_versus[ i ] = 0
						}
					}
					// client_print(id, print_chat, "BPS - *TERRORIS = ID = 1 Activado* PASSE.!")
					client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1")
					return PLUGIN_CONTINUE
				}
			}
			else {
				// client_print(id, print_chat, "BPS - *EL STATS, ESTA DESACTIVADO* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_OFF_ID")
				return PLUGIN_CONTINUE
			}
		}
		else {
			// client_print(id, print_chat, "BPS - *NO TIENES EL ID=1* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
	}
	return PLUGIN_CONTINUE
}

public points_tied( id, level, cid )
{
	if ( !cmd_access( id, level, cid, 1 )) return PLUGIN_HANDLED
	
	new Players[ MAXPLAYERS ]
	new iNum
	new i
	
	get_players( Players, iNum, "ch" )
	for( --iNum; iNum >= 0; iNum-- )
	{
		i = Players[ iNum ]
		if(bps_players[i] == 15)
		{
			// client_print(id, print_chat, "BPS - *TERRORIS = ID = 15 Desactivado* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
		if(bps_players[i] == 1)
		{
			if( get_pcvar_num( pcvarToggle2 ) )
			{
				if( !CheckUserIgnored( i ))
				{
					switch( cs_get_user_team( i ))
					{
						case( CS_TEAM_T ):
						{
							g_szPoints_rws[ i ] += 1
							g_szPoints_rp[ i ] += 1
							bps_players_versus[ i ] = 0
						}
						case( CS_TEAM_CT ):
						{
							g_szPoints_rws[ i ] += 1
							g_szPoints_rp[ i ] += 1
							bps_players_versus[ i ] = 0
						}
					}
					// client_print(id, print_chat, "BPS - *TERRORIS = ID = 1 Activado* PASSE.!")
					client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_ACT_ID_1")
					return PLUGIN_CONTINUE
				}
			}
			else {
				// client_print(id, print_chat, "BPS - *EL STATS, ESTA DESACTIVADO* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_OFF_ID")
				return PLUGIN_CONTINUE
			}
		}
		else {
			// client_print(id, print_chat, "BPS - *NO TIENES EL ID=1* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
	}
	return PLUGIN_CONTINUE
}

public bomb_planted( planter )
{
	new id
	new Players[ MAXPLAYERS ]
	new iNum
	get_players( Players, iNum, "ch" )
	if(bps_players[planter] == 1)
	{
		if(get_pcvar_num(pcvarToggle2))
		{
			if(get_playersnum() >= 2)
			{
				g_szPoints_bp[ planter ] += 1
				g_szPoints[ planter ] += 3
				//client_print(id, print_chat, "BPS - *PLANTAR C4 Contado* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_PLANT_C4")
				return PLUGIN_CONTINUE
			}
			else {
				// client_print(id, print_chat, "BPS - *PLANTAR, 2 JUGADOR MINIMO* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_PLANT_C4_MINI")
				return PLUGIN_CONTINUE
			}
			} else {
			// client_print(id, print_chat, "BPS - *EL STATS, ESTA DESACTIVADO* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_OFF_ID")
			return PLUGIN_CONTINUE
		}
		} else {
		//client_print(id, print_chat, "BPS - *PLANTAR, NO TIENES EL ID=1* PASSE.!")
		client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
		return PLUGIN_CONTINUE
	}
}

public bomb_explode( planter, defuser )
{
	new id
	new Players[ MAXPLAYERS ]
	new iNum
	get_players( Players, iNum, "ch" )
	if(bps_players[planter] == 1)
	{
		if(get_pcvar_num(pcvarToggle2))
		{
			if(get_playersnum() >= 2)
			{
				g_szCSW_C4[ planter ] += 1
				g_szPoints[ planter ] += 5
				// client_print(id, print_chat, "BPS - *EXPLOCION Marcados* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_EXPLO_C4")
				return PLUGIN_CONTINUE
			}
			else {
				// client_print(id, print_chat, "BPS - *EXPLOCION, 2 JUGADOR MINIMO* PASSE.!")
				client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_EXPLO_C4_MINI")
				return PLUGIN_CONTINUE
			}
			} else {
			// client_print(id, print_chat, "BPS - *EL STATS, ESTA DESACTIVADO* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_OFF_ID")
			return PLUGIN_CONTINUE
		}
		} else {
		// client_print(id, print_chat, "BPS - *EXPLOCION, NO TIENES EL ID=1* PASSE.!")
		client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
		return PLUGIN_CONTINUE
	}
}

public bomb_defused( defuser )
{
	new id
	new Players[ MAXPLAYERS ]
	new iNum
	get_players( Players, iNum, "ch" )
	if(bps_players[defuser] == 1)
	{
		if(get_pcvar_num(pcvarToggle2))
		{
			g_szPoints[defuser] += 15
			g_szPoints_bd[ defuser ] += 1
			// client_print(id, print_chat, "BPS - *DEFUSER ID = 1* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DEFUSE")
			return PLUGIN_CONTINUE
			} else {
			// client_print(id, print_chat, "BPS - *EL STATS, ESTA DESACTIVADO* PASSE.!")
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_OFF_ID")
			return PLUGIN_CONTINUE
		}
		} else {
		// client_print(id, print_chat, "BPS - *NO TIENES EL ID=1* PASSE.!")
		client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
		return PLUGIN_CONTINUE
	}
}

public EventNewRound()
{
	g_bRoundEnded = false;
}

public EventRoundEnd()
{
	g_bRoundEnded = true;
	
	new Players[MAXPLAYERS], iNum, i;
	get_players(Players, iNum, "ch"); // Obtenemos jugadores humanos conectados
	
	for (new idx = 0; idx < iNum; idx++)
	{
		i = Players[idx];
		
		if (bps_players[i] == 1)
		{
			// --- LÓGICA DE MULTIKILLS AL FIN DE RONDA ---
			switch (g_iCurrentKills[i])
			{
				case 2: { 
					g_szPoints_2k[i]++; 
					g_szPoints[i] += 5;  // Puntos extra por el 2K
				}
				case 3: { 
					g_szPoints_3k[i]++; 
					g_szPoints[i] += 10; // Puntos extra por el 3K
				}
				case 4: { 
					g_szPoints_4k[i]++; 
					g_szPoints[i] += 15; // Puntos extra por el 4K
				}
				default: {
					if (g_iCurrentKills[i] >= 5)
					{
						g_szPoints_5k[i]++; 
						g_szPoints[i] += 20; // Puntos extra por el 5K+
					}
				}
			}
			set_task(1.0, "SavePointsAtRoundEnd", CONNECT_TASK3 + i);
		}
	}
}

public SavePointsAtRoundEnd(taskid)
{
	// Recuperamos el ID real restando la misma base exacta
	new i = taskid - CONNECT_TASK3;
	
	// Verificamos por seguridad que el índice esté dentro del rango de jugadores válidos
	if (!is_user_connected(i))
	{
		return;
	}
	
	// Verificamos nuevamente que tenga el sistema activo
	if (bps_players[i] == 1)
	{
		// Ejecutamos las funciones de guardado exclusivamente para este jugador
		CheckLevelAndSave1(i);
		CheckLevelAndSave2(i);
		CheckLevelAndSave3(i);
		CheckLevelAndSave4(i);
		
		// Notificamos individualmente al jugador
		client_print_color(i, print_team_default, "^4%s ^1%L", pug_panama, i, "BPS_DATA_SAVE");
	}
	else
	{
		client_print_color(i, print_team_default, "^4%s ^1%L", pug_panama, i, "BPS_OFF_ID");
	}
}

public CheckLevelAndSave1( id ) {
	
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "'", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "^"", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "`", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "´", "*" )
	
	new SQL_TABLE1[256]
	get_cvar_string("bps_sql_db_1",SQL_TABLE1,256)
	
	new szTemp[512]
	formatex( szTemp, charsmax( szTemp ), "UPDATE %s SET nick = '%s', \
	skillpoints = '%i', \
	level = '%i', \
	pug_k = '%i', \
	pug_d = '%i', \
	pug_a = '%i', \
	pug_bp = '%i', \
	pug_bd = '%i', \
	pug_adr = '%i', \
	pug_hsp = '%i', \
	pug_rws = '%i', \
	pug_win = '%i', \
	pug_los = '%i', \
	pug_tied = '%i', \
	pug_r_los = '%i', \
	pug_rp = '%i' WHERE authid = '%s'", 
	SQL_TABLE1, g_szName[ id ], 
	g_szPoints[id], 
	g_szLevels[id], 
	g_szPoints_k[id], 
	g_szPoints_d[id], 
	g_szPoints_a[id], 
	g_szPoints_bp[id], 
	g_szPoints_bd[id], 
	g_szPoints_adr[id], 
	g_szPoints_hsp[id], 
	g_szPoints_rws[id], 
	g_szPoints_win[id], 
	g_szPoints_los[id], 
	g_szPoints_tied[id], 
	g_szPoints_r_los[id], 
	g_szPoints_rp[id], g_szAuthID[id] )
	SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
	// client_print(id, print_chat, "BPS - *Se Guardo los Datos #1* PASSE.!")
}

public CheckLevelAndSave2( id ) {
	
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "'", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "^"", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "`", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "´", "*" )
	
	new SQL_TABLE2[256]
	get_cvar_string("bps_sql_db_2",SQL_TABLE2,256)
	
	new szTemp[512]
	formatex( szTemp, charsmax( szTemp ), "UPDATE %s SET nick = '%s', \
	pug_CSW_GLOCK18 = '%i', \
	pug_CSW_USP = '%i', \
	pug_CSW_P228 = '%i', \
	pug_CSW_DEAGLE = '%i', \
	pug_CSW_ELITE = '%i', \
	pug_CSW_FIVESEVEN = '%i', \
	pug_CSW_KNIFE = '%i', \
	pug_CSW_HEGRENADE = '%i', \
	pug_CSW_C4 = '%i' WHERE authid = '%s'", 
	SQL_TABLE2, g_szName[ id ], 
	g_szCSW_GLOCK18[ id ], 
	g_szCSW_USP[ id ], 
	g_szCSW_P228[ id ], 
	g_szCSW_DEAGLE[ id ], 
	g_szCSW_ELITE[ id ], 
	g_szCSW_FIVESEVEN[ id ], 
	g_szCSW_KNIFE[ id ], 
	g_szCSW_HEGRENADE[ id ], 
	g_szCSW_C4[ id ], g_szAuthID[id] )
	SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
	// client_print(id, print_chat, "BPS - *Se Guardo los Datos #2* PASSE.!")
}

public CheckLevelAndSave3( id ) {
	
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "'", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "^"", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "`", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "´", "*" )
	
	new SQL_TABLE3[256]
	get_cvar_string("bps_sql_db_3",SQL_TABLE3,256)
	
	new szTemp[512]
	formatex( szTemp, charsmax( szTemp ), "UPDATE %s SET nick = '%s', \
	pug_CSW_M3 = '%i', \
	pug_CSW_XM1014 = '%i', \
	pug_CSW_TMP = '%i', \
	pug_CSW_UMP45 = '%i', \
	pug_CSW_MAC10 = '%i', \
	pug_CSW_MP5NAVY = '%i', \
	pug_CSW_P90 = '%i', \
	pug_CSW_GALIL = '%i', \
	pug_CSW_FAMAS = '%i', \
	pug_CSW_AK47 = '%i', \
	pug_CSW_M4A1 = '%i', \
	pug_CSW_SCOUT = '%i', \
	pug_CSW_SG552 = '%i', \
	pug_CSW_AWP = '%i', \
	pug_CSW_G3SG1 = '%i', \
	pug_CSW_AUG = '%i', \
	pug_CSW_SG550 = '%i', \
	pug_CSW_M249 = '%i' WHERE authid = '%s'", 
	SQL_TABLE3, g_szName[ id ], 
	g_szCSW_M3[ id ], 
	g_szCSW_XM1014[ id ], 
	g_szCSW_TMP[ id ], 
	g_szCSW_UMP45[ id ], 
	g_szCSW_MAC10[ id ], 
	g_szCSW_MP5NAVY[ id ], 
	g_szCSW_P90[ id ], 
	g_szCSW_GALIL[ id ], 
	g_szCSW_FAMAS[ id ], 
	g_szCSW_AK47[ id ], 
	g_szCSW_M4A1[ id ], 
	g_szCSW_SCOUT[ id ], 
	g_szCSW_SG552[ id ], 
	g_szCSW_AWP[ id ], 
	g_szCSW_G3SG1[ id ], 
	g_szCSW_AUG[ id ], 
	g_szCSW_SG550[ id ], 
	g_szCSW_M249[ id ], g_szAuthID[id] )
	SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
	// client_print(id, print_chat, "BPS - *Se Guardo los Datos #3* PASSE.!")
}

public CheckLevelAndSave4( id ) {
	
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "'", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "^"", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "`", "*" )
	replace_all( g_szName[ id ], charsmax( g_szName[ ] ), "´", "*" )
	
	new SQL_TABLE4[256]
	get_cvar_string("bps_sql_db_4",SQL_TABLE4,256)
	
	new szTemp[512]
	formatex( szTemp, charsmax( szTemp ), "UPDATE %s SET nick = '%s', \
	pug_2k = '%i', \
	pug_3k = '%i', \
	pug_4k = '%i', \
	pug_5k = '%i', \
	pug_v1 = '%i', \
	pug_v2 = '%i', \
	pug_v3 = '%i', \
	pug_v4 = '%i', \
	pug_v5 = '%i' WHERE authid = '%s'", 
	SQL_TABLE4, g_szName[ id ], 
	g_szPoints_2k[id], 
	g_szPoints_3k[id], 
	g_szPoints_4k[id], 
	g_szPoints_5k[id], 
	g_szPoints_v1[id], 
	g_szPoints_v2[id], 
	g_szPoints_v3[id], 
	g_szPoints_v4[id], 
	g_szPoints_v5[id], g_szAuthID[id] )
	SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
	// client_print(id, print_chat, "BPS - *Se Guardo los Datos #4* PASSE.!")
}

public LoadPoints1( id ) {
	new Data[ 1 ]
	Data[ 0 ] = id
	
	new SQL_TABLE1[256]
	get_cvar_string("bps_sql_db_1",SQL_TABLE1,256)
	
	new szTemp[512]
	format( szTemp, charsmax( szTemp ), 
	"SELECT skillpoints, \
	level, \
	pug_k, \
	pug_d, \
	pug_a, \
	pug_bp, \
	pug_bd, \
	pug_adr, \
	pug_hsp, \
	pug_rws, \
	pug_win, \
	pug_los, \
	pug_tied, \
	pug_r_los, \
	pug_rp FROM %s WHERE authid = '%s'", 
	SQL_TABLE1, g_szAuthID[ id ] )
	SQL_ThreadQuery( g_SqlTuple, "RegisterClient1", szTemp, Data, 1 )
}

public LoadPoints2( id ) {
	new Data[ 1 ]
	Data[ 0 ] = id
	
	new SQL_TABLE2[256]
	get_cvar_string("bps_sql_db_2",SQL_TABLE2,256)
	
	new szTemp[512]
	format( szTemp, charsmax( szTemp ), 
	"SELECT pug_CSW_GLOCK18, \
	pug_CSW_USP, \
	pug_CSW_P228, \
	pug_CSW_DEAGLE, \
	pug_CSW_ELITE, \
	pug_CSW_FIVESEVEN, \
	pug_CSW_KNIFE, \
	pug_CSW_HEGRENADE, \
	pug_CSW_C4 FROM %s WHERE authid = '%s'", 
	SQL_TABLE2, g_szAuthID[ id ] )
	SQL_ThreadQuery( g_SqlTuple, "RegisterClient2", szTemp, Data, 1 )
}

public LoadPoints3( id ) {
	new Data[ 1 ]
	Data[ 0 ] = id
	
	new SQL_TABLE3[256]
	get_cvar_string("bps_sql_db_3",SQL_TABLE3,256)
	
	new szTemp[512]
	format( szTemp, charsmax( szTemp ), 
	"SELECT pug_CSW_M3, \
	pug_CSW_XM1014, \
	pug_CSW_TMP, \
	pug_CSW_UMP45, \
	pug_CSW_MAC10, \
	pug_CSW_MP5NAVY, \
	pug_CSW_P90, \
	pug_CSW_GALIL, \
	pug_CSW_FAMAS, \
	pug_CSW_AK47, \
	pug_CSW_M4A1, \
	pug_CSW_SCOUT, \
	pug_CSW_SG552, \
	pug_CSW_AWP, \
	pug_CSW_G3SG1, \
	pug_CSW_AUG, \
	pug_CSW_SG550, \
	pug_CSW_M249 FROM %s WHERE authid = '%s'", 
	SQL_TABLE3, g_szAuthID[ id ] )
	SQL_ThreadQuery( g_SqlTuple, "RegisterClient3", szTemp, Data, 1 )
}

public LoadPoints4(id) {
	new Data[ 1 ]
	Data[ 0 ] = id
	
	new SQL_TABLE4[256]
	get_cvar_string("bps_sql_db_4",SQL_TABLE4,256)
	
	new szTemp[512]
	format( szTemp, charsmax( szTemp ), 
	"SELECT pug_2k, \
	pug_3k, \
	pug_4k, \
	pug_5k, \
	pug_v1, \
	pug_v2, \
	pug_v3, \
	pug_v4, \
	pug_v5 FROM %s WHERE authid = '%s'", 
	SQL_TABLE4, g_szAuthID[ id ] )
	SQL_ThreadQuery( g_SqlTuple, "RegisterClient4", szTemp, Data, 1 )
}

public RegisterClient1( FailState, Handle:Query, Error[ ], Errcode, Data[ ], DataSize )
{
	new id
	id = Data[ 0 ]
	new SQL_TABLE1[256]
	
	g_szPoints[ id ] = 0
	g_szLevels[ id ] = 0
	g_szPoints_k[ id ] = 0
	g_szPoints_d[ id ] = 0
	g_szPoints_a[ id ] = 0
	g_szPoints_bp[ id ] = 0
	g_szPoints_bd[ id ] = 0
	g_szPoints_adr[ id ] = 0
	g_szPoints_hsp[ id ] = 0
	g_szPoints_rws[ id ] = 0
	g_szPoints_win[ id ] = 0
	g_szPoints_los[ id ] = 0
	g_szPoints_tied[ id ] = 0
	g_szPoints_r_los[ id ] = 0
	g_szPoints_rp[ id ] = 0
	
	get_cvar_string("bps_sql_db_1",SQL_TABLE1,256)
	if( !SQL_IsFail( FailState, Errcode, Error ) )
	{
		if( SQL_NumResults( Query ) < 1 )
		{
			new szTemp[ 512 ]
			format( szTemp, charsmax( szTemp ), "INSERT INTO %s \
			(authid, nick, skillpoints, level, pug_k, pug_d, pug_a, pug_bp,  pug_bd, pug_adr, pug_hsp, pug_rws, pug_win, pug_los, pug_tied, pug_r_los, pug_rp ) \
			VALUES( '%s', '%s', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i' )", 
			SQL_TABLE1, g_szAuthID[id], g_szName[id], 
			g_szPoints[id], 
			g_szLevels[id], 
			g_szPoints_k[id], 
			g_szPoints_d[id], 
			g_szPoints_a[id], 
			g_szPoints_bp[id], 
			g_szPoints_bd[id], 
			g_szPoints_adr[id], 
			g_szPoints_hsp[id], 
			g_szPoints_rws[id], 
			g_szPoints_win[id], 
			g_szPoints_los[id], 
			g_szPoints_tied[id], 
			g_szPoints_r_los[id], 
			g_szPoints_rp[id] )
			SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
		}
		else
		{
			g_szPoints[ id ] = SQL_ReadResult( Query, 0 )
			g_szLevels[ id ] = SQL_ReadResult( Query, 1 )
			g_szPoints_k[ id ] = SQL_ReadResult( Query, 2 )
			g_szPoints_d[ id ] = SQL_ReadResult( Query, 3 )
			g_szPoints_a[ id ] = SQL_ReadResult( Query, 4 )
			g_szPoints_bp[ id ] = SQL_ReadResult( Query, 5 )
			g_szPoints_bd[ id ] = SQL_ReadResult( Query, 6 )
			g_szPoints_adr[ id ] = SQL_ReadResult( Query, 7 )
			g_szPoints_hsp[ id ] = SQL_ReadResult( Query, 8 )
			g_szPoints_rws[ id ] = SQL_ReadResult( Query, 9 )
			g_szPoints_win[ id ] = SQL_ReadResult( Query, 10 )
			g_szPoints_los[ id ] = SQL_ReadResult( Query, 11 )
			g_szPoints_tied[ id ] = SQL_ReadResult( Query, 12 )
			g_szPoints_r_los[ id ] = SQL_ReadResult( Query, 13 )
			g_szPoints_rp[ id ] = SQL_ReadResult( Query, 14 )
		}
	}
}

public RegisterClient2( FailState, Handle:Query, Error[ ], Errcode, Data[ ], DataSize )
{
	new id
	id = Data[ 0 ]
	new SQL_TABLE2[256]
	
	g_szCSW_GLOCK18[id] = 0
	g_szCSW_USP[id] = 0
	g_szCSW_P228[id] = 0
	g_szCSW_DEAGLE[id] = 0
	g_szCSW_ELITE[id] = 0
	g_szCSW_FIVESEVEN[id] = 0
	g_szCSW_KNIFE[id] = 0
	g_szCSW_HEGRENADE[id] = 0
	g_szCSW_C4[id] = 0
	
	get_cvar_string("bps_sql_db_2",SQL_TABLE2,256)
	if( !SQL_IsFail( FailState, Errcode, Error ) )
	{
		if( SQL_NumResults( Query ) < 1 )
		{
			new szTemp[ 512 ]
			format( szTemp, charsmax( szTemp ), "INSERT INTO %s \
			(authid, nick, pug_CSW_GLOCK18, pug_CSW_USP, pug_CSW_P228, pug_CSW_DEAGLE, pug_CSW_ELITE, pug_CSW_FIVESEVEN, pug_CSW_KNIFE, pug_CSW_HEGRENADE, pug_CSW_C4) \
			VALUES( '%s', '%s', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i' )", 
			SQL_TABLE2, g_szAuthID[id], g_szName[id], 
			g_szCSW_GLOCK18[id], 
			g_szCSW_USP[id], 
			g_szCSW_P228[id], 
			g_szCSW_DEAGLE[id], 
			g_szCSW_ELITE[id], 
			g_szCSW_FIVESEVEN[id], 
			g_szCSW_KNIFE[id], 
			g_szCSW_HEGRENADE[id], 
			g_szCSW_C4[id] )
			SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
		}
		else
		{
			g_szCSW_GLOCK18[id] = SQL_ReadResult( Query, 0 )
			g_szCSW_USP[id] = SQL_ReadResult( Query, 1 )
			g_szCSW_P228[id] = SQL_ReadResult( Query, 2 )
			g_szCSW_DEAGLE[id] = SQL_ReadResult( Query, 3 )
			g_szCSW_ELITE[id] = SQL_ReadResult( Query, 4 )
			g_szCSW_FIVESEVEN[id] = SQL_ReadResult( Query, 5 )
			g_szCSW_KNIFE[id] = SQL_ReadResult( Query, 6 )
			g_szCSW_HEGRENADE[id] = SQL_ReadResult( Query, 7 )
			g_szCSW_C4[id] = SQL_ReadResult( Query, 8 )
		}
	}
}

public RegisterClient3( FailState, Handle:Query, Error[ ], Errcode, Data[ ], DataSize )
{
	new id
	id = Data[ 0 ]
	new SQL_TABLE3[256]
	
	g_szCSW_M3[id] = 0
	g_szCSW_XM1014[id] = 0
	g_szCSW_TMP[id] = 0
	g_szCSW_UMP45[id] = 0
	g_szCSW_MAC10[id] = 0
	g_szCSW_MP5NAVY[id] = 0
	g_szCSW_P90[id] = 0
	g_szCSW_GALIL[id] = 0
	g_szCSW_FAMAS[id] = 0
	g_szCSW_AK47[id] = 0
	g_szCSW_M4A1[id] = 0
	g_szCSW_SCOUT[id] = 0
	g_szCSW_SG552[id] = 0
	g_szCSW_AWP[id] = 0
	g_szCSW_G3SG1[id] = 0
	g_szCSW_AUG[id] = 0
	g_szCSW_SG550[id] = 0
	g_szCSW_M249[id] = 0
	
	get_cvar_string("bps_sql_db_3",SQL_TABLE3,256)
	if( !SQL_IsFail( FailState, Errcode, Error ) )
	{
		if( SQL_NumResults( Query ) < 1 )
		{
			new szTemp[ 512 ]
			format( szTemp, charsmax( szTemp ), "INSERT INTO %s \
			(authid, nick, pug_CSW_M3, pug_CSW_XM1014, pug_CSW_TMP, pug_CSW_UMP45, pug_CSW_MAC10, pug_CSW_MP5NAVY, pug_CSW_P90, \
			pug_CSW_GALIL, pug_CSW_FAMAS, pug_CSW_AK47, pug_CSW_M4A1, pug_CSW_SCOUT, pug_CSW_SG552, pug_CSW_AWP, pug_CSW_G3SG1, pug_CSW_AUG, pug_CSW_SG550, pug_CSW_M249 ) \
			VALUES( '%s', '%s', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i' )", 
			SQL_TABLE3, g_szAuthID[id], g_szName[id], 
			g_szCSW_M3[id], 
			g_szCSW_XM1014[id], 
			g_szCSW_TMP[id], 
			g_szCSW_UMP45[id], 
			g_szCSW_MAC10[id], 
			g_szCSW_MP5NAVY[id], 
			g_szCSW_P90[id], 
			g_szCSW_GALIL[id], 
			g_szCSW_FAMAS[id], 
			g_szCSW_AK47[id], 
			g_szCSW_M4A1[id], 
			g_szCSW_SCOUT[id], 
			g_szCSW_SG552[id], 
			g_szCSW_AWP[id], 
			g_szCSW_G3SG1[id], 
			g_szCSW_AUG[id], 
			g_szCSW_SG550[id], 
			g_szCSW_M249[id] )
			SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
		}
		else
		{
			g_szCSW_M3[id] = SQL_ReadResult( Query, 0 )
			g_szCSW_XM1014[id] = SQL_ReadResult( Query, 1 )
			g_szCSW_TMP[id] = SQL_ReadResult( Query, 2 )
			g_szCSW_UMP45[id] = SQL_ReadResult( Query, 3 )
			g_szCSW_MAC10[id] = SQL_ReadResult( Query, 4 )
			g_szCSW_MP5NAVY[id] = SQL_ReadResult( Query, 5 )
			g_szCSW_P90[id] = SQL_ReadResult( Query, 6 )
			g_szCSW_GALIL[id] = SQL_ReadResult( Query, 7 )
			g_szCSW_FAMAS[id] = SQL_ReadResult( Query, 8 )
			g_szCSW_AK47[id] = SQL_ReadResult( Query, 9 )
			g_szCSW_M4A1[id] = SQL_ReadResult( Query, 10 )
			g_szCSW_SCOUT[id] = SQL_ReadResult( Query, 11 )
			g_szCSW_SG552[id] = SQL_ReadResult( Query, 12 )
			g_szCSW_AWP[id] = SQL_ReadResult( Query, 13 )
			g_szCSW_G3SG1[id] = SQL_ReadResult( Query, 14 )
			g_szCSW_AUG[id] = SQL_ReadResult( Query, 15 )
			g_szCSW_SG550[id] = SQL_ReadResult( Query, 16 )
			g_szCSW_M249[id] = SQL_ReadResult( Query, 17 )
		}
	}
}

public RegisterClient4( FailState, Handle:Query, Error[ ], Errcode, Data[ ], DataSize )
{
	new id
	id = Data[ 0 ]
	new SQL_TABLE4[256]
	
	g_szPoints_2k[id] = 0
	g_szPoints_3k[id] = 0
	g_szPoints_4k[id] = 0
	g_szPoints_5k[id] = 0
	g_szPoints_v1[id] = 0
	g_szPoints_v2[id] = 0
	g_szPoints_v3[id] = 0
	g_szPoints_v4[id] = 0
	g_szPoints_v5[id] = 0
	
	get_cvar_string("bps_sql_db_4",SQL_TABLE4,256)
	if( !SQL_IsFail( FailState, Errcode, Error ) )
	{
		if( SQL_NumResults( Query ) < 1 )
		{
			new szTemp[ 512 ]
			format( szTemp, charsmax( szTemp ), "INSERT INTO %s \
			(authid, nick, pug_2k, pug_3k, pug_4k, pug_5k, pug_v1, pug_v2, pug_v3, pug_v4, pug_v5 ) \
			VALUES( '%s', '%s', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i', '%i' )", 
			SQL_TABLE4, g_szAuthID[id], g_szName[id], 
			g_szPoints_2k[id], 
			g_szPoints_3k[id], 
			g_szPoints_4k[id], 
			g_szPoints_5k[id], 
			g_szPoints_v1[id], 
			g_szPoints_v2[id], 
			g_szPoints_v3[id], 
			g_szPoints_v4[id], 
			g_szPoints_v5[id] )
			SQL_ThreadQuery( g_SqlTuple, "IgnoreHandle", szTemp )
		}
		else
		{
			g_szPoints_2k[id] = SQL_ReadResult( Query, 0 )
			g_szPoints_3k[id] = SQL_ReadResult( Query, 1 )
			g_szPoints_4k[id] = SQL_ReadResult( Query, 2 )
			g_szPoints_5k[id] = SQL_ReadResult( Query, 3 )
			g_szPoints_v1[id] = SQL_ReadResult( Query, 4 )
			g_szPoints_v2[id] = SQL_ReadResult( Query, 5 )
			g_szPoints_v3[id] = SQL_ReadResult( Query, 6 )
			g_szPoints_v4[id] = SQL_ReadResult( Query, 7 )
			g_szPoints_v5[id] = SQL_ReadResult( Query, 8 )
		}
	}
	Test_bps_players(id)
}

public IgnoreHandle( FailState, Handle:Query, Error[ ], Errcode, Data[ ], DataSize )
{
	SQL_FreeHandle( Query )
}

public stats_pug(id)
{
	static Text[190]
	read_args(Text, charsmax(Text))
	remove_quotes(Text)
	
	if(equali(Text, ".stats"))
	{
		if(bps_players[id] == 1)
		{
			SkillRank(id)
			return PLUGIN_CONTINUE
		}
		if(bps_players[id] == 15)
		{
			client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_DESACT_ID_15")
			return PLUGIN_CONTINUE
		}
	}
	if(equali(Text, ".top"))
	{
		pug_stats_top(id)
		return PLUGIN_CONTINUE
	}
	if(equali(Text, ".top15"))
	{
		pug_stats_top(id)
		return PLUGIN_CONTINUE
	}
	return PLUGIN_CONTINUE
}

public pug_stats_temp(id)
{
	new web_temp_pug_stats[256]
	get_cvar_string("pug_web_temp_pug",web_temp_pug_stats,256)
	if( get_pcvar_num( pcvarToggle_stats ) == 0 )
	{
		client_print_color(id, print_team_default, "^4%s ^1%L", pug_panama, LANG_PLAYER, "BPS_STATS_PUG")
		return PLUGIN_CONTINUE
	}
	if( get_pcvar_num( pcvarToggle_stats ) == 1 )
	{
		show_motd(id, web_temp_pug_stats, "BASIC POINTS STATS")
		return PLUGIN_CONTINUE
	}
	return PLUGIN_HANDLED
}

public pug_stats_top(id)
{
	new web_top_pug_stats[256]
	get_cvar_string("pug_web_top_pug",web_top_pug_stats,256)
	
	show_motd(id, web_top_pug_stats, "BASIC POINTS STATS")
	
	return PLUGIN_HANDLED
}

public motd_pug_end()
{
	new web_temp_pug_stats[256]
	get_cvar_string("pug_web_temp_pug",web_temp_pug_stats,256)
	show_motd(0, web_temp_pug_stats, "BASIC POINTS STATS")
	return PLUGIN_HANDLED
}

public SkillRank( id )
{
	new SQL_TABLE1[256]
	get_cvar_string("bps_sql_db_1",SQL_TABLE1,256)
	
	new Data[ 1 ]
	Data[ 0 ] = id
	
	new szTemp[ 512 ]
	format( szTemp, charsmax( szTemp ), "SELECT COUNT(*) FROM %s WHERE pug_k >= %i", SQL_TABLE1, g_szPoints_k[ id ])
	SQL_ThreadQuery( g_SqlTuple, "GetTotalRows", szTemp, Data, 1 )
	
	return PLUGIN_CONTINUE
}

public GetTotalRows( FailState, Handle:Query, Error[ ], Errcode, Data[ ], DataSize )
{
	new id
	id = Data[ 0 ]
	
	if( !SQL_IsFail( FailState, Errcode, Error ) )
	{
		static szName[32], Info[1501], len; 
		get_user_name(id, szName, charsmax(szName))
		len = format(Info, 1500,"<body bgcolor=#FFFFFF><font color=#FFFFFF><pre>");
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>Player:</B><font color=^"#000000^">%s</color></left>^n", szName);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>Frags:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_k[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>Death:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_d[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>Assists:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_a[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>Bomb plant:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_bp[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>Bomb Defuse:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_bd[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>2K:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_2k[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>3K:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_3k[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>4K:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_4k[id]);
		len += format(Info[len], 1500-len,"<left><font color=^"#000000^"><B>5K:</B><font color=^"#000000^">%i</color></left>^n", g_szPoints_5k[id]);
		show_motd(id, Info, "BASIC POINTS STATS");
	}
}

SQL_IsFail( FailState, Errcode, Error[ ] ) {
	if( FailState == TQUERY_CONNECT_FAILED )
	{
		log_amx( "[Error] Could not connect to SQL database: %s", Error )
		return true
	}
	if( FailState == TQUERY_QUERY_FAILED )
	{
		log_amx( "[Error] Query failed: %s", Error )
		return true
	}
	if( Errcode )
	{
		log_amx( "[Error] Error on query: %s", Error )
		return true
	}
	return false
}
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang2070\\ f0\\ fs16 \n\\ par }
*/
